name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install coinor-cbc
        python -m pip install --upgrade pip
        pip install flake8==3.8.3 black==19.10b0 pytest==5.4.3
        pip install -e .
    - name: Test with pytest
      run: |
        black --check ./slotmachine ./tests
        flake8
        pytest
